### ISSUE TITLE
Add TLS and basic user authentication support for Prometheus communication

### ISSUE THREAD

**Issue by YasDoud** [woblerr/pgbackrest_exporter#19]
Hello,
Please, can you add TLS support and basic user authentication for Prometheus communication like it already was done for node_exporter
using the `https://github.com/prometheus/exporter-toolkit`

**Comment by woblerr** [comment]
Hi,
I will try to look this issue soon.

**Comment by woblerr** [comment]
Hello,
Added in #22.

**Comment by YasDoud** [comment]
@woblerr Thank you very much for such a fast resolution of this request! 
Looking forward to the release.

**Comment by woblerr** [comment]
@YasDoud 
[v0.10.0](https://github.com/woblerr/pgbackrest_exporter/releases/tag/v0.10.0) is now available.
