### ISSUE TITLE
Dashboard for Grafana ?

### ISSUE THREAD

**Issue by n1nj444** [woblerr/pgbackrest_exporter#39]
Hi,

The exporter is working well on all of my pgbackrest nodes, but there is a grafana dashboard to visualize all of theses metrics please ?

Regards,

**Comment by woblerr** [comment]
Hi

I will add an example of a dashboard in the near future.

**Comment by woblerr** [comment]
I added in #43 a link to an example dashboard for visualizing metrics in Grafana.
