### ISSUE TITLE
Add parameter web.listen-address

### ISSUE THREAD

**Issue by feelan03** [woblerr/pgbackrest_exporter#52]
Hello.
Thank you very much for your exporter. Helps a lot at work. I wanted to suggest adding web.listen-address to the launch options. The default value is 127.0.0.1 or localhost. Allows you to assign an exporter to a specific ip. This functionality is available in absolutely every exporter. I would like to see it in this exporter as well. Thank you

**Comment by woblerr** [comment]
Hi

I implemented the flags from the [exporter-toolkit](https://github.com/prometheus/exporter-toolkit) package v0.9.1. I think this will solve this issue.

This update turned out to be a little more complex, so it will require additional testing. However, you can try it now. See #53.

**Comment by woblerr** [comment]
Now available in version [v0.14.0](https://github.com/woblerr/pgbackrest_exporter/releases/tag/v0.14.0).
