### ISSUE TITLE
[New Feature] Expose metrics regarding last database backup size and duration

### ISSUE THREAD

**Issue by d-mankowski-synerise** [woblerr/pgbackrest_exporter#55]
Hello,

I would like to ask to expose 2 new metrics for each stanza:

`pgbackrest_backup_last_backup_size_bytes` and `pgbackrest_backup_last_backup_duration_seconds`. I somehow managed to modify a dashboard to visualize it:

<img width="609" alt="image" src="https://github.com/woblerr/pgbackrest_exporter/assets/101267779/082159e9-30d7-4368-91ff-420873a92896">

<img width="977" alt="image" src="https://github.com/woblerr/pgbackrest_exporter/assets/101267779/fcddcffb-4f05-4e50-a0a5-31a5e241bf7a">

which assumes that there is a date included in backup's name, but most likely this will not always be true. It was difficult to achieve this in Grafana and I don't think it is possible to achieve it in plain PromQL, but should be fairly easy to do in golang. Thx in advance

**Comment by woblerr** [comment]
Hi

Added this metrics as part of #61. So I'm closing this issue.

**Comment by d-mankowski-synerise** [comment]
Thanks! Waiting for the release :)
