### ISSUE TITLE
[New Feature] Expose metric regarding backup errors, but only since the last full backup

### ISSUE THREAD

**Issue by d-mankowski-synerise** [woblerr/pgbackrest_exporter#56]
`pgbackrest_backup_error_status` is a really good metric, but it is not really possible (at least in an easy way) to create any alerts based on it. For example, let's say that I have one stanza, for which full backup is made weekly (and incremental - every day) and the other one, for which full backup is made monthly (and differential every day). In terms of alerts, the only thing we should care about, is the answer to question "are we able to restore database by using the last full back and all the incremental backups/last differential backup, created onwards".

So, what I am thinking about, is some metric per stanza, like `pgbackrest_backup_errors_since_last_full_backup`, that would take into the account the following:

- `pgbackrest_backup_error_status` of the last full backup,
- (`pgbackrest_backup_error_status` of all the incremental backups made after the last full backup) OR (`pgbackrest_backup_error_status` of the last differential  backup), depending on which type we are using

and the returned value would be `0`, if all `pgbackrest_backup_error_status` returned 0, or `1` otherwise

**Comment by woblerr** [comment]
Hi

Thank you for your request.

Suppose, the new metric `pgbackrest_backup_errors_since_last_full_backup` is active (equal `1`) and what we should do?
You still need to go into the dashboard, see which backup contains the error and try to fix it. Otherwise, you can get serious problems.

I agree that it may be a little difficult to build simple alert based on `pgbackrest_backup_error_status` metric, because the metric will be active as long as there is a backup containing an error.
However, as soon as such a backup appeared, you immediately need to understand the cause of the error, otherwise you have problems.

I plan to add additional metrics for the latest backups (as part of #55).
One of them will show whether the last backup contains an error.
Maybe this is exactly what you need.

**Comment by d-mankowski-synerise** [comment]
> Suppose, the new metric pgbackrest_backup_errors_since_last_full_backup is active (equal 1) and what we should do?

We should do a full new backup, so in case of a failure we will be able to restore the most recent data. And if this succeeds, then `pgbackrest_backup_errors_since_last_full_backup` would change its value to `0`.

> However, as soon as such a backup appeared, you immediately need to understand the cause of the error, otherwise you have problems.

Totally agree, but in order to spot an issue, I need an alert. And having an alert that can never be closed does not make sense. Basically, the metric I am proposing would cause an alert to be active in the following period of time: `<timestamp when the faulty backup was made>; <full new backup without any errors>`.

> I plan to add additional metrics for the latest backups (as part of https://github.com/woblerr/pgbackrest_exporter/issues/55).
One of them will show whether the last backup contains an error.
Maybe this is exactly what you need.

In case of a full backup - sure. In case of incremental and differential backups, not so much, at least on the first thought. The other thing I can think of would be to include a new label in `pgbackrest_backup_error_status` metric - `full_backup_name`. Then, we could do something like this:

`sum by (full_backup_name) (pgbackrest_backup_error_status)` and somehow join it with some metric from #55

**Comment by woblerr** [comment]
> We should do a full new backup, so in case of a failure we will be able to restore the most recent data. And if this succeeds, then `pgbackrest_backup_errors_since_last_full_backup` would change its value to `0`.

It seems there is a misunderstanding of the meaning of the `pgbackrest_backup_error_status` metric.

This metric shows whether the backup contains a page checksum error. 
This metric does not show whether the backup was completed with an error or not. If a backup has been created, it has been created.

Therefore, if the PG contains errors in the checksums - it's data corruption. Creating a new full backup will not solve the problem. It will also contain a checksum error. It's necessary to fix data corruption in PG.

**Comment by d-mankowski-synerise** [comment]
> Therefore, if the PG contains errors in the checksums - it's data corruption. Creating a new full backup will not solve the problem. It will also contain a checksum error. It's necessary to fix data corruption in PG.

Ok, I missed the step "fix data corruption with fsck or something" before creating a new, full backup - but wouldn't the logic for an alert still be valid?

**Comment by woblerr** [comment]
In this case, it is enough to set up alerts for errors in latest backup. 

If there is a data corruption error in the PG, the metric will show that the last backup contains this error. And you should immediately fix it.

If the corruption is fixed, then after creating the next backup, the metric will show that there is no data corruption error in the last backup.

When you want to restore from backup, you need to understand at what moment the data corruption error was fixed and recover after that moment (for example, using PITR).
And for this you need to see which backups in the backup chain contain/don't contain a data corruption error.

In general, after fixing a data corruption error, it's not necessary to do a full backup. Recommended but not necessary. You can continue to use the existing backup chain, you just need to remember that some backups may contain corrupted data. However, in further backups, this data no longer contains  data corruption errors.

**Comment by d-mankowski-synerise** [comment]
Makes sense, I think we can close this. Thanks for the elaboration.
