### ISSUE TITLE
[bug] `pgbackrest_backup_since_last_completion_seconds` ignores backup type

### ISSUE THREAD

**Issue by d-mankowski-synerise** [woblerr/pgbackrest_exporter#58]
Exporter version: 0.14.0

pgBackRest version: plenty (I checked it for 2.32, 2.37, 2.41, 2.43, 2.44)

We use only full and incremental backups (thanks to the exporter and the dashboard I noticed that compressed full backup has the same size as an uncompressed incremental one, so we will stop using the latter), and as can be seen on the picture below - exporter exposes some metrics `pgbackrest_backup_since_last_completion_seconds{backup_type="diff"}`, while it should not. This is the first problem.

<img width="1574" alt="image" src="https://github.com/woblerr/pgbackrest_exporter/assets/101267779/e8b97daf-7f76-4fb8-8e83-5f1415ce28ef">

<img width="1904" alt="image" src="https://github.com/woblerr/pgbackrest_exporter/assets/101267779/7c547209-68a6-4677-ad8e-a20d8f0c0743">

<img width="1915" alt="image" src="https://github.com/woblerr/pgbackrest_exporter/assets/101267779/37ab8f4e-a974-4e2b-8518-fb848276d209">

The second problem is, that it reports that full backup and incremental backup were done at the same time, while it is not true:

```
        full backup: 20230603-003004F
            timestamp start/stop: 2023-06-03 00:30:04 / 2023-06-03 01:26:55
            wal start/stop: 00000002000007B2000000CC / 00000002000007B2000000CD
            database size: 406.3GB, database backup size: 406.3GB
            repo1: backup set size: 67.4GB, backup size: 67.4GB

        incr backup: 20230603-003004F_20230604-003003I
            timestamp start/stop: 2023-06-04 00:30:03 / 2023-06-04 01:13:30
            wal start/stop: 00000002000007B5000000A9 / 00000002000007B5000000A9
            database size: 406.7GB, database backup size: 311GB
            repo1: backup set size: 67.5GB, backup size: 49GB
            backup reference list: 20230603-003004F

        incr backup: 20230603-003004F_20230605-003004I
            timestamp start/stop: 2023-06-05 00:30:04 / 2023-06-05 01:10:38
            wal start/stop: 00000002000007B70000004B / 00000002000007B70000004F
            database size: 406.9GB, database backup size: 290.1GB
            repo1: backup set size: 67.5GB, backup size: 44.9GB
            backup reference list: 20230603-003004F, 20230603-003004F_20230604-003003I

        incr backup: 20230603-003004F_20230606-003004I
            timestamp start/stop: 2023-06-06 00:30:04 / 2023-06-06 01:13:05
            wal start/stop: 00000002000007B9000000D1 / 00000002000007B9000000D1
            database size: 407GB, database backup size: 308.9GB
            repo1: backup set size: 67.5GB, backup size: 48.7GB
            backup reference list: 20230603-003004F, 20230603-003004F_20230604-003003I, 20230603-003004F_20230605-003004I

        incr backup: 20230603-003004F_20230607-003004I
            timestamp start/stop: 2023-06-07 00:30:04 / 2023-06-07 01:13:28
            wal start/stop: 00000002000007BC000000D6 / 00000002000007BC000000D8
            database size: 407.4GB, database backup size: 311.4GB
            repo1: backup set size: 67.6GB, backup size: 49GB
            backup reference list: 20230603-003004F, 20230603-003004F_20230604-003003I, 20230603-003004F_20230605-003004I, 20230603-003004F_20230606-003004I

        incr backup: 20230603-003004F_20230608-003004I
            timestamp start/stop: 2023-06-08 00:30:04 / 2023-06-08 01:13:54
            wal start/stop: 00000002000007C000000032 / 00000002000007C000000034
            database size: 407.8GB, database backup size: 313.6GB
            repo1: backup set size: 67.7GB, backup size: 49.1GB
            backup reference list: 20230603-003004F, 20230603-003004F_20230604-003003I, 20230603-003004F_20230605-003004I, 20230603-003004F_20230606-003004I, 20230603-003004F_2023

        incr backup: 20230603-003004F_20230609-003004I
            timestamp start/stop: 2023-06-09 00:30:04 / 2023-06-09 01:10:41
            wal start/stop: 00000002000007C1000000F9 / 00000002000007C1000000FB
            database size: 408.0GB, database backup size: 290.4GB
            repo1: backup set size: 67.7GB, backup size: 45.2GB
            backup reference list: 20230603-003004F, 20230603-003004F_20230604-003003I, 20230603-003004F_20230605-003004I, 20230603-003004F_20230606-003004I, 20230603-003004F_20230607-003004I, 20230603-003004F_20230608-003004I

        full backup: 20230610-003004F
            timestamp start/stop: 2023-06-10 00:30:04 / 2023-06-10 01:27:20
            wal start/stop: 00000002000007C4000000F2 / 00000002000007C4000000F4
            database size: 408.4GB, database backup size: 408.4GB
            repo1: backup set size: 67.8GB, backup size: 67.8GB

<end of pgbackrest info output>
```

**Comment by woblerr** [comment]
Hi

The main logic for `pgbackrest_backup_since_last_completion_seconds` and `pgbackrest_backup_last_databases` metrics is:
* differential backup is always based on last full;
* if the last backup was full, the metric will take full backup value;
* incremental backup is always based on last full or differential;
* if the last backup was full or differential, the metric will take full or differential backup value.

Perhaps it should be in the documentation.

**Comment by d-mankowski-synerise** [comment]
Thanks for the answer, it explains the behavior, but could you elaborate what is the exact reason behind this logic? To me exporter right now exposes metrics, that are incorrect (for instance, if pgBackRest does only full backups, then why would there be any metrics regarding incremental or differential backups?)

**Comment by woblerr** [comment]
The logic is based on a backup chain and the dependence that diff and incr are tied to the full.
Making a flashing metric is not a good idea.

If you know for sure that you are not creating, for example, diff backups, you can ignore the metric with the diff label.

**Comment by woblerr** [comment]
I added information about the logic of setting values for `pgbackrest_*_last_*` metrics for diff and incr backups. See b19c383 commit.

**Comment by d-mankowski-synerise** [comment]
LGTM, thanks
