### ISSUE TITLE
EXPORTER_ Except for tls, does it have SSH for config? My pgbackrest is backed up using SSH encryption free method

### ISSUE THREAD

**Issue by Iatbzh** [woblerr/pgbackrest_exporter#65]
EXPORTER_ Except for tls, does it have SSH for config? My pgbackrest is backed up using SSH encryption free method

**Comment by woblerr** [comment]
Hi

I didn't quite understand the question.
The metrics are collected based on result of `pgbackrest info --output json` command. Thus, the exporter calls the command and parses the received response.
Which protocol pgBackRest uses depends on its settings.
