### ISSUE TITLE
Newbie: Only Stanza Name Exported

### ISSUE THREAD

**Issue by prime-minister-of-fun** [woblerr/pgbackrest_exporter#81]
Hi,
Per the title, I'm a newbie at this, so maybe I'm missing something.  Running under systemd, or even just manually, there is no data exported about my backups.
This is on RHEL8, selinux enabled.  FWIW, if your hosts have selinux enabled, you **will** need audit2allow to sort out permissions.
My package source of pgbackrest are the Percona repos.
Here's how I run it to watch. 
`su -s /bin/sh -c "pgbackrest_exporter --web.listen-address=localhost:9854 --backrest.config=/etc/pgbackrest.conf --backrest.stanza-include=foo-all-dev --backrest.verbose-wal --backrest.database-count --backrest.database-count-latest --backrest.backup-type=full --log.level=debug --backrest.database-parallel-processes=4" exporter`

EDITED:
I figured it out,  What I needed to do was run this first to be sure I got my permissions right:
`su -s /bin/sh -c "pgbackrest info --output json" exporter`
The "99" error code in the exporter was now obvious, as was the reason for the error code.

Thank you so much for this project!

**Comment by woblerr** [comment]
Hi

Yes, you did the right check. It's great that everything worked out.
