### ISSUE TITLE
Running systemd service as root fails when repo is on NFS

### ISSUE THREAD

**Issue by gclough** [woblerr/pgbackrest_exporter#90]
It seems that if the filesystem where the repo is located doesn't honour the `root` PID, then the systemd service can't access the repo and the exporter fails to gather any data.

Could we please get some convenient way to configure the service to run under a non-root custom username?

**Comment by gclough** [comment]
FYI @dmitry-sinina, as you seem to have made the most recent update to this file.

**Comment by woblerr** [comment]
The metrics are collected based on result of `pgbackrest info --output json` command. pgBackRest must be configured correctly to execute the command.

To run the service not  under `root`, you can specify `useUser=` and `Group=` in the `[Service]` section of the unit file.
