### ISSUE TITLE
example service template does interesting things

### ISSUE THREAD

**Issue by step21** [woblerr/pgbackrest_exporter#91]
afaict, the example service template will use the additional arguments as part of the metrics endpoint. which seems kind of pointless? For me `Environment="ARGS=--web.endpoint=/metrics --web.listen-address=:9854 --collect.interval=600"` meant that the endpoint was literally `/metrics --web.listen-address=:9854 --collect.interval=600`

**Comment by woblerr** [comment]
Thanks, fixed.

**Comment by step21** [comment]
Thank you, glad to be able to help.
